sudo: required
language: node_js
node_js:
- lts/*
services:
- docker
script:
- cd client
- npm install -g create-react-app
- npm install
- npm run build
- npm run docker:build
before_deploy:
- sudo apt-get update && sudo apt-get install -y apt-transport-https
- curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
- sudo touch /etc/apt/sources.list.d/kubernetes.list
- echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
- sudo apt-get update
- sudo apt-get install -y kubectl
- echo "Successfully installed kubectl"
- export KUBECONFIG=$TRAVIS_BUILD_DIR/kubeconfig
- curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
- chmod +x ./aws-iam-authenticator
- cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$HOME/bin:$PATH
- kubectl cluster-info --context=aws-us-east --kubeconfig=$TRAVIS_BUILD_DIR/kubeconfig
- kubectl get pods -l app=eth-madness-compare --context=aws-us-east --kubeconfig=$TRAVIS_BUILD_DIR/kubeconfig
deploy:
  skip_cleanup: true
  provider: script
  script: bash $TRAVIS_BUILD_DIR/deploy.sh
  on:
    repo: nodesmith/eth-madness
    branch: compare
env:
  global:
  - AWS_DEFAULT_REGION=us-east-2
  - secure: F1ZYnn4AyL5QurUSxHh4+/pHRqmEkTfKeIDJ8foXG+WgoqsUPaDVAaR5XOPphTGc259SFDDEbL34b3REZMk7YGoRvTQp0n87f/KU2pbb3sJ+3MxN52dvfHnIKqSOKRNntjp+1ffqvKHul9VZniuhY41kpeQhzbU6kTdyobhBkyEiL1EiTW73jQMS3uEODaAIxhfAlh+U7HcMq04Ne0msOpsf11TMQFeB45Aoq+e3berIz2FBfB9F1Q/CV9Niw4eBkB+cGU8zcOBnDz1SaTrmfWRpPXF2vMGt+L4F86n9gWAIlmCsxifohD4hwAYFwNV0IDOJKASSqdpZOI5oboMxpg7n3il5D+NIVbuGYVZOT9nyH/ePBZo2zRp7MUgpEnTyqvA5zPoC5LlU23QpkoWKiFemtLxsNfFkcziMVspgOaDK7ewqQO0/8k1/Jy+5Ai0xELSdqUmmK3GAFamAJKqewjOcs8JmyPkzH3ep+g8TSG5BXFcPx2Anl93fjRuvlZjnVRxRxyG5OUwUvmJPPa6+ARI6vAJIX+NYOAV2SymlMDDMMllw7WIceWQHn25/evgR9vNNRTQ3/ULoWoyONIEHDqUVzO4E4j1Mzp5ArDPEQ50Dybb3gyhi1aUoQlupizMO3rQ+PZDZ6s3VXdOPhRCN3g/ZJQMSptv59oxhCa+Ehy4=
  - secure: EM2yt4sLsZM1uv3OzG0pl5+iMnA91AYYSKX4umnH9WVION+X1eIP7GbrRJDDqFV6IIww060Zn048GsJ7UQs1eZp62viqowynmRPLF0ICE/JvuRTLuqQ1A49ZhuLaFs9jW/mq0md0dPRuVQW4LLuJUX0RdcBjK6V6LD/E+cbswpqYYcPrtLZXpQCm/d1bk5vWXQYe9buo2NVvwFdEgSkHt2d7hHi93xY0Dxr+SZzoijt53PMX+e8ChVg9mabHDk2uU3IsxXQn0uED7b9cEs2jYCdkQHHQPmTDn2sZXyAXmRIf79QlefXetgexcn5LjFk5DVeC9aoQE1isTz0nDxGR93chTnrsHIxu05NG9EBg08brgfjmawHDvCjtw8vT9t+KYtLDWmyHH0d9W/+il8/O+X26HZq5uWgkN3IXZy1CtieYgg+nM+En1nZRPArgcHJdJHaueCgLWNqftGfqejQw7ssBiI11ad6VyIUKQzhJhNykybvCoBFKSh14KK6e1PZS2fz8PsVuz7JIXOkTwqw8sZsRk3Qp4s4T2ds7RdYf+0llr9rNDMJQ+0nASsPqJo06vhrIhyFHsN2fqEDRCNpiQX1SCZdH57mqBdABteXprsPeZcWxtC0jYgkIcm/ayKd6nag4ai8a2Hb3CVnLu7JzZyNy5ED5F5k6JYdoWlsWB0E=
  - secure: x7OGKc2+CokNQw4bnDxUgm7G/Ls/jlamX708ZRUdyLsNK9t3fvLMSPb32YCVSQkNHF50rS0VnwkdDBdEnqhsKxrz+X2xjGXY0FBFz3XpZld/lAEtxXLY6vmW9KtzXgy2RxXIgXeujKID4kmBBXqoiyJfiWjHh3W7okkKtSUtYLkbphp22j0ekVQSLDGqBQKeh+p+ncTbtSsga8rmE09yIzDQaHrTZZ5l2kQ4BUlOG4vPBRMLMG7Uv2AQWzJNzF6j9UkmLSg4k7Ixrgj3gZbZhW1kMqx0xSfuWfu8P6TuapX8NEA3PBtrF1bmYb/SKSrQx/9LZ63+8enhYtH0SMEy0JjdQMyVa3qNRVyrAnjdbp1f7r4+L5doTUeHSm4RoSxRINt4x8nH+1y0SttSHmNNm84CSFP/Gq9eBRLJaZZcRQHlZrZxr7NMqJMC7wZvEnvZjMC8eVe4Wl1K2+JUT7WaauurrGjEMg7HB+9sJn+f6NiEcIqWWfGjvfDAMGR1KSRg1KreBU+72KgRYnf11Hy1UEx84radTvn0Pt1JPDnrHZXLTkWgQSmCukfYIGqJB+yio+x0974peywYqEOlDcfrNaQm0f3tHwRONmcu4azdGT2tVR46fCtSy7i+qUKYQ6inYx2/hSS7WTo9nhCvULTX+0bURFL+1X0oNZhH11bWsKc=
  - secure: jvVcMGE6gzJEvs165qmJC8gFDCiAiAnCpRq8WO03Bskgx0acv0L0Tou7DUZUlXTlbQsE22fGe3bDvGU17x/soDa44VSvhPaGodk9MSTRlA6J1IePGMsdpRlfaOI2VQWh7aGSodnnOUdLpOgIfzivtCJeNDIGWqlVDiinL3+ZUNP0bR9FN0scczEetCKzLcYE3LYj0szOKVJ0PgXcfWvpAAzpaFxDH3cgc+7jci1SxsCiHgiKu+dOcvCyO2O/P/Vpw4VIxu1Vg96YZ+1OmHnGcyHhOIdWAz0D+9QoihMV01ZH8clpjDc3YpbBEM9/EtC+Rp4bZL1FtcjgvAfU3LCer8qX4pMeslbJU/XVDHk/Vw7OUsRrf7vOzglTnrljaW4o+xNhBjT2RJv3IhmyPXxNo80eUIRzwsV/SMpHVhfVQ0sWSf8QjFxUmgqFqYHZj9M+Tm0NIkmFrJyfCdux6IckbWO06siULGQY1Ea+by32T6J5ErsO41qeVu6jFKFzsJfHmAIJYwWqbFWRqgXYZExbtZz9CHGSfxQU1SdoQbsijIOoBFvPPeKOPdoKFfggOAj3ecPJQzgX3gmzGNl4jPSSo8IH7wSkjfSipn3o8qmbvAfp76vMx8SGfP+EJVWGFSKmXVMYyHackvZ8YsmVkGyvrTTr88LDQkMKXdslKr5Qm/w=
