apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: eth-madness-compare
  name: eth-madness-compare
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eth-madness-compare
  template:
    metadata:
      labels:
        app: eth-madness-compare
    spec:
      containers:
      - image: nodesmith/eth-madness:latest
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 10Mi
      imagePullSecrets:
      - name: docker-hub

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: eth-madness-compare
  name: eth-madness-compare
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: eth-madness-compare
  type: ClusterIP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/issuer: letsencrypt-production
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: eth-madness-compare
spec:
  rules:
  - host: compare.ethmadness.com
    http:
      paths:
      - backend:
          serviceName: eth-madness-compare
          servicePort: 80
  tls:
  - hosts:
    - compare.ethmadness.com
    secretName: eth-madness-compare-cert
